name: "Build (Java)"

on:
  workflow_call:
    inputs:
      java_version:
        description: "The version of the jdk to use."
        type: number
        default: 25
        required: false
      gradle_build_tasks:
        description: "The build tasks for building the project."
        type: string
        default: "build"
        required: false
      gradle_artifacts_path:
        description: "The location of the files to upload/publish."
        type: string
        required: true
      gradle_publish:
        description: "Whether the project should be published."
        type: boolean
        default: true
        required: false
      release:
        description: "Whether we are in release mode."
        type: boolean
        default: false
        required: false
      release_name_template:
        description: "The template to use for releases."
        type: string
        default: "{0} release"
        required: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions: {}

env:
  ORG_GRADLE_PROJECT_release: ${{ inputs.release }}

jobs:
  action:
    name: "Action"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Checkout CI Scripts"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: xpdustry/.github
          path: .github/shared-ci
          sparse-checkout: |
            scripts

      - name: "Validate Version and Changelog"
        id: validate
        run:
          .github/shared-ci/scripts/version-validate.sh VERSION.txt
          echo "version=$(cat VERSION.txt)" >> $GITHUB_OUTPUT
          .github/shared-ci/scripts/changelog-extract.sh CURRENT_CHANGELOG_BODY.md

      - name: "Setup Java ${{ inputs.java_version }}"
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          java-version: "${{ inputs.java_version }}"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: "Build Gradle Project"
        run: ./gradlew ${{ inputs.gradle_build_tasks }}

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: artifacts
          path: ${{ inputs.gradle_artifacts_path }}
          if-no-files-found: error

      - name: "Upload Test Results"
        if: ${{ always() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: test-results
          path: |
            **/build/test-results/test/TEST-*.xml
            build/reports/
            */build/reports/

      - name: "Publish to Maven"
        if: ${{ inputs.gradle_publish && (inputs.release || startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/dev')) }}
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_MAVEN_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_MAVEN_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_PASSWORD }}"

      - name: "Publish to Github"
        if: ${{ inputs.release }}
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: v${{ steps.validate.outputs.version }}
          name: ${{ format(inputs.release_name_template, 'v' + steps.validate.outputs.version) }}
          body_path: CURRENT_CHANGELOG_BODY.md
          files: ${{ inputs.gradle_artifacts_path }}
          preserve_order: true
          make_latest: true
          target_commitish: ${{ github.ref }}

      - name: "Bump Version and Update Changelog"
        if: ${{ inputs.release }}
        run: |
          git config --local user.email "ci@xpdustry.com"
          git config --local user.name "Xpdustry CI"
          .github/shared-ci/scripts/version-increment.sh VERSION.txt
          git add VERSION.txt
          .github/shared-ci/scripts/changelog-update.sh CHANGELOG.md CHANGELOG.md "$(cat VERSION.txt)"
          git add CHANGELOG.md
          git commit -m "chore(release): Bump version and update changelog and "
          git push

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: "Upload Event File"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: event-file
          path: ${{ github.event_path }}