name: "Build (Java)"

on:
  workflow_call:
    inputs:
      java_version:
        description: "The version of the JDK to use."
        type: string
        default: "25"
        required: false
      gradle_build_tasks:
        description: "The build tasks for building the project."
        type: string
        default: "build"
        required: false
      gradle_publish:
        description: "Whether the project should be published."
        type: boolean
        default: true
        required: false
      gradle_publish_tasks:
        description: "The publish tasks for publishing the project."
        type: string
        default: "publish"
        required: false
      gradle_version_bump_task:
        description: "Custom Gradle task to bump the version."
        type: string
        default: ""
        required: false
      version_file:
        description: "File containing the project version."
        type: string
        default: "build.gradle.kts"
        required: false
      artifacts_path:
        description: "The location of the files to upload/publish."
        type: string
        required: true
      release:
        description: "Whether we are in release mode."
        type: boolean
        default: false
        required: false
      release_name_template:
        description: "The template to use for releases."
        type: string
        default: "v{0} release"
        required: false
    secrets:
      XPDUSTRY_MAVEN_USERNAME:
        required: false
      XPDUSTRY_MAVEN_PASSWORD:
        required: false
      XPDUSTRY_MAVEN_SIGNING_KEY:
        required: false
      XPDUSTRY_MAVEN_SIGNING_PASSWORD:
        required: false
      XPDUSTRY_GRADLE_PORTAL_KEY:
        required: false
      XPDUSTRY_GRADLE_PORTAL_SECRET:
        required: false

concurrency:
  group: "${{ github.workflow }}-${{ github.event.number || github.ref }}"
  cancel-in-progress: true

permissions: {}

env:
  ORG_GRADLE_PROJECT_release: ${{ inputs.release }}

jobs:
  action:
    name: "Action"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:

      - name: "Checkout Repository"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: "Checkout CI Scripts"
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6
        with:
          repository: xpdustry/.github
          path: .xpdustry-ci
          sparse-checkout: scripts

      - name: "Setup Java ${{ inputs.java_version }}"
        uses: actions/setup-java@f2beeb24e141e01a676f977032f5a29d81c9e27e # v5
        with:
          java-version: "${{ inputs.java_version }}"
          distribution: "temurin"

      - name: "Setup Gradle"
        uses: gradle/actions/setup-gradle@4d9f0ba0025fe599b4ebab900eb7f3a1d93ef4c2 # v5

      - name: "Validate Version"
        id: version
        run: |
          version="$(./gradlew properties -q | grep '^version:' | cut -d ':' -f 2 | tr -d '[:space:]')"
          .xpdustry-ci/scripts/version-validate.sh "$version" "${{ inputs.release }}"
          echo "version=$version" >> "$GITHUB_OUTPUT"

      - name: "Validate Changelog"
        run: .xpdustry-ci/scripts/extract-changelog-body.sh "CHANGELOG.md" "RELEASE_BODY.md"

      - name: "Build Gradle"
        run: ./gradlew ${{ inputs.gradle_build_tasks }}

      - name: "Upload Artifacts"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: artifacts
          path: ${{ inputs.artifacts_path }}
          if-no-files-found: error

      - name: "Upload Test Results"
        if: ${{ always() }}
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: test-results
          path: |
            **/build/test-results/test/TEST-*.xml
            **/build/reports/

      - name: "Publish to GitHub"
        if: ${{ inputs.release }}
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: ${{ format(inputs.release_name_template, steps.version.outputs.version) }}
          body_path: RELEASE_BODY.md
          files: ${{ inputs.artifacts_path }}
          preserve_order: true
          make_latest: true
          target_commitish: ${{ github.ref }}

      - name: "Publish to Maven"
        if: ${{ inputs.gradle_publish && (inputs.release || startsWith(github.ref, 'refs/heads/master') || startsWith(github.ref, 'refs/heads/dev')) }}
        run: ./gradlew ${{ inputs.gradle_publish_tasks }}
        env:
          ORG_GRADLE_PROJECT_xpdustryUsername: "${{ secrets.XPDUSTRY_MAVEN_USERNAME }}"
          ORG_GRADLE_PROJECT_xpdustryPassword: "${{ secrets.XPDUSTRY_MAVEN_PASSWORD }}"
          ORG_GRADLE_PROJECT_signingKey: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_KEY }}"
          ORG_GRADLE_PROJECT_signingPassword: "${{ secrets.XPDUSTRY_MAVEN_SIGNING_PASSWORD }}"
          ORG_GRADLE_PROJECT_pluginPortalApiKey: "${{ secrets.XPDUSTRY_GRADLE_PORTAL_KEY }}"
          ORG_GRADLE_PROJECT_pluginPortalApiSecret: "${{ secrets.XPDUSTRY_GRADLE_PORTAL_SECRET }}"

      - name: "Update Changelog"
        if: ${{ inputs.release }}
        run: .xpdustry-ci/scripts/changelog-update.sh "CHANGELOG.md" "${{ steps.version.outputs.version }}"

      - name: "Bump Version"
        if: ${{ inputs.release }}
        run: |
          gradle_version_bump_task="${{ inputs.gradle_version_bump_task }}"
          if [[ -n "$gradle_version_bump_task" ]]; then
            ./gradlew "$gradle_version_bump_task"
          else
            .xpdustry-ci/scripts/bump-version.sh "${{ inputs.version_file }}" "${{ steps.version.outputs.version }}"
          fi

      - name: "Commit Release Changes"
        if: ${{ inputs.release }}
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit_message: "chore(release): Post v${{ steps.version.outputs.version }} changes"
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref || github.ref_name }}
          file_pattern: "${{ inputs.version_file }} CHANGELOG.md"

  event_file:
    name: "Event File"
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:

      - name: "Upload Event File"
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6
        with:
          name: event-file
          path: ${{ github.event_path }}